# NumPy Assignment – Day 10


## 1. Import NumPy

In [ ]:
import numpy as np

## 2. Create an Array

In [ ]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


## 3. Dimensions, Shape, Data Type

In [ ]:
a=np.array(10)
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim,b.ndim,c.ndim,d.ndim)
print(a.shape,b.shape,c.shape,d.shape)
print(c.dtype,d.dtype)
print(type(a),type(b))
print(len(b))

0 1 2 3
() (3,) (2, 3) (2, 2, 3)
int64 int64
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
3


## 5. arange() and eye()

In [ ]:
print(np.arange(1,11))
print(np.arange(1,11,2))
print(np.eye(3))

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
